import discord
import asyncio
from src.languages.localize import _
from src.utils.database import get_db, get_language
from src.utils.logger import get_cool_logger
from src.languages import lang_constants as lang_constants
from src.utils.embeds import get_embed_icon
import config.constants as constants


logger = get_cool_logger(__name__)


class TicketControlPanel(discord.ui.View):
    """Control panel for closed tickets with Transcript, Reopen, and Delete buttons."""

    def __init__(self, ticket_id: int, user: discord.User, category_name: str):
        super().__init__(timeout=None)
        self.ticket_id = ticket_id
        self.user = user
        self.category_name = category_name
        self.transcript_button.custom_id = f"ticket_transcript_{ticket_id}"
        self.reopen_button.custom_id = f"ticket_reopen_{ticket_id}"
        self.delete_button.custom_id = f"ticket_delete_{ticket_id}"

    @discord.ui.button(label="Transcript", style=discord.ButtonStyle.secondary, emoji=lang_constants.TRANSCRIPT_EMOJI, custom_id="transcript_btn")
    async def transcript_button(self, button: discord.ui.Button, interaction: discord.Interaction):
        await interaction.response.defer(ephemeral=True)

        try:
            # Local import to avoid circular import with create_ticket
            from src.features.tickets.create_transcript import create_transcript

            transcript_file = await create_transcript(interaction.channel)
            file = discord.File(
                transcript_file, filename=f"ticket-{self.ticket_id}-transcript.txt")

            if constants.TICKET_LOG_CHANNEL_ID:
                log_channel = interaction.guild.get_channel(
                    constants.TICKET_LOG_CHANNEL_ID)
                if log_channel:
                    embed = discord.Embed(
                        title=lang_constants.TRANSCRIPT_EMOJI + " Ticket Transcript",
                        description=f"**Ticket ID:** {self.ticket_id}\n**User:** {self.user.mention}\n**Category:** {self.category_name}\n**Generated by:** {interaction.user.mention}",
                        color=constants.DISCORD_EMBED_COLOR
                    )
                    embed.set_footer(text=constants.DISCORD_MESSAGE_TRADEMARK,
                                     icon_url=get_embed_icon(interaction))
                    await log_channel.send(embed=embed, file=file)

            transcript_file.seek(0)
            user_file = discord.File(
                transcript_file, filename=f"ticket-{self.ticket_id}-transcript.txt")
            await interaction.followup.send(lang_constants.SUCCESS_EMOJI + " Transcript created and sent to log channel!", file=user_file, ephemeral=True)
            logger.info(
                f"Transcript created for ticket #{self.ticket_id} by {interaction.user.id}")
        except Exception as e:
            logger.error(f"Error creating transcript: {e}")
            await interaction.followup.send(lang_constants.ERROR_EMOJI + " Failed to create transcript.", ephemeral=True)

    @discord.ui.button(label="Reopen", style=discord.ButtonStyle.success, emoji=lang_constants.UNLOCK_EMOJI, custom_id="reopen_btn")
    async def reopen_button(self, button: discord.ui.Button, interaction: discord.Interaction):
        is_support = (
            interaction.user.id in constants.TICKET_SUPPORT_USER_IDS or
            (constants.TICKET_SUPPORT_ROLE_ID and any(
                role.id == constants.TICKET_SUPPORT_ROLE_ID for role in interaction.user.roles))
        )

        if not is_support:
            await interaction.response.send_message(lang_constants.ERROR_EMOJI + " Only support staff can reopen tickets.", ephemeral=True)
            return

        await interaction.response.defer()

        # Local import to avoid circular import with create_ticket
        from src.features.tickets.view.CloseTicketView import CloseTicketView
        from src.features.tickets.send_dm_notification import send_dm_notification

        try:
            db = await get_db()
            if not await db.reopen_ticket(self.ticket_id):
                await interaction.followup.send(lang_constants.ERROR_EMOJI + " Failed to reopen ticket.", ephemeral=True)
                return

            # Restore user permissions
            await interaction.channel.set_permissions(
                self.user,
                read_messages=True,
                send_messages=True,
                attach_files=True,
                embed_links=True,
                read_message_history=True
            )

            # Delete the control panel message
            await interaction.message.delete()

            # Send new message with close button
            embed = discord.Embed(
                title=lang_constants.UNLOCK_EMOJI + " Ticket Reopened",
                description=f"This ticket has been reopened by {interaction.user.mention}.\n{self.user.mention} can now continue the conversation.",
                color=constants.SUCCESS_EMBED_COLOR
            )
            embed.set_footer(text=constants.DISCORD_MESSAGE_TRADEMARK,
                             icon_url=get_embed_icon(interaction))

            close_view = CloseTicketView(
                self.ticket_id, self.user, self.category_name)
            await interaction.channel.send(embed=embed, view=close_view)

            # Log the reopen
            if constants.TICKET_LOG_CHANNEL_ID:
                log_channel = interaction.guild.get_channel(
                    constants.TICKET_LOG_CHANNEL_ID)
                if log_channel:
                    log_embed = discord.Embed(
                        title=lang_constants.UNLOCK_EMOJI + " Ticket Reopened",
                        description=f"**Ticket ID:** {self.ticket_id}\n**User:** {self.user.mention}\n**Category:** {self.category_name}\n**Reopened by:** {interaction.user.mention}",
                        color=constants.SUCCESS_EMBED_COLOR
                    )
                    log_embed.set_footer(
                        text=constants.DISCORD_MESSAGE_TRADEMARK, icon_url=get_embed_icon(interaction))
                    await log_channel.send(embed=log_embed)

            # Send DM to user with channel link
            await send_dm_notification(self.user, self.ticket_id, "reopened", interaction.channel, interaction.user, interaction.client.user)
            logger.info(
                f"Ticket #{self.ticket_id} reopened by {interaction.user.id}")
        except Exception as e:
            logger.error(f"Error reopening ticket: {e}")
            await interaction.followup.send(lang_constants.ERROR_EMOJI + " Failed to reopen ticket.", ephemeral=True)

    @discord.ui.button(label="Delete", style=discord.ButtonStyle.danger, emoji=lang_constants.TRASH_EMOJI, custom_id="delete_btn")
    async def delete_button(self, button: discord.ui.Button, interaction: discord.Interaction):
        is_support = (
            interaction.user.id in constants.TICKET_SUPPORT_USER_IDS or
            (constants.TICKET_SUPPORT_ROLE_ID and any(
                role.id == constants.TICKET_SUPPORT_ROLE_ID for role in interaction.user.roles))
        )

        if not is_support:
            await interaction.response.send_message(lang_constants.ERROR_EMOJI + " Only support staff can delete tickets.", ephemeral=True)
            return

        lang = await get_language(interaction.user.id)
        delete_msg = _(
            "tickets.delete_countdown", lang)

        embed = discord.Embed(
            title=lang_constants.TRASH_EMOJI + " " + _("tickets.deleting", lang),
            description=delete_msg,
            color=constants.FAILED_EMBED_COLOR
        )
        embed.set_footer(text=constants.DISCORD_MESSAGE_TRADEMARK,
                         icon_url=get_embed_icon(interaction))

        await interaction.response.send_message(embed=embed)

        # Log the deletion
        if constants.TICKET_LOG_CHANNEL_ID:
            log_channel = interaction.guild.get_channel(
                constants.TICKET_LOG_CHANNEL_ID)
            if log_channel:
                log_embed = discord.Embed(
                    title=lang_constants.TRASH_EMOJI + " Ticket Deleted",
                    description=f"**Ticket ID:** {self.ticket_id}\n**User:** {self.user.mention}\n**Category:** {self.category_name}\n**Deleted by:** {interaction.user.mention}",
                    color=constants.FAILED_EMBED_COLOR
                )
                log_embed.set_footer(
                    text=constants.DISCORD_MESSAGE_TRADEMARK, icon_url=get_embed_icon(interaction))
                await log_channel.send(embed=log_embed)

        await asyncio.sleep(5)

        # Delete ticket from database
        try:
            db = await get_db()
            await db.delete_ticket(self.ticket_id)
        except Exception as e:
            logger.error(f"Failed to delete ticket from database: {e}")

        await interaction.channel.delete(reason=f"Ticket #{self.ticket_id} deleted by {interaction.user.name}")
        logger.info(
            f"Ticket #{self.ticket_id} deleted by {interaction.user.id}")
