DISCORD_MESSAGE_TRADEMARK = "BebraLand team 🚀🌍🎮"
DISCORD_EMBED_COLOR = 0x714C35
DISCORD_PREFIX = "!"

ACTION_CONFIRMATION_MESSAGE_DELETE_DELAY = 60

USER_WELCOME_ENABLED = True
WELCOME_FORCE_DEFAULT_FOOTER = True
